### ISSUE TITLE
some browsers attempt to autocomplete the search feild

### ISSUE THREAD

**Issue by FunkyQChicken** [twentytwoo/startpages#1]
Firefox tries to autocomplete the google bar in sapphire with tons of useless suggestions (i.e. usernames, searches on websites AND google history), anyway, it looks ugly and can be prevented by adding `autocomplete="off"`
  
```
<form method="get" action="https://www.google.co.uk/search?q=">
	<input class="wf-mplus1p" name="q" id="search" type="text" placeholder="あなたは本当に生きている？" />
</form>

```
to 
```
<form method="get" action="https://www.google.co.uk/search?q=">
	<input class="wf-mplus1p" name="q" id="search" type="text" placeholder="あなたは本当に生きている？" autocomplete="off"/>
</form>```

**Comment by twentytwoo** [comment]
Thanks for the tip. You could submit a pull request next time...

**Comment by twentytwoo** [comment]
Fixed 7b4550e

**Comment by FunkyQChicken** [comment]
sorry, I'll do that next time, I'm still getting used to Github
